# Generated by Django 2.2.2 on 2019-06-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portrait',
            name='order',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='award',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='portrait',
            name='image',
            field=models.ImageField(upload_to='myapp/images/'),
        ),
    ]
