# Generated by Django 2.2.2 on 2019-06-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190613_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='portrait',
            name='identifier',
            field=models.CharField(default='k', max_length=200),
            preserve_default=False,
        ),
    ]
