# Generated by Django 2.2.2 on 2019-06-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_portrait_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='portrait',
            name='overlay_text',
            field=models.CharField(default='caption', max_length=50),
            preserve_default=False,
        ),
    ]
