# Generated by Django 2.2.3 on 2019-07-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_portrait_overlay_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='portrait',
            name='myid',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
